// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPxx-hcRbbp3tqaaHQyxMJHcuM7btny4',
    appId: '1:346917753378:web:0145ab4f2dde49fffdb07b',
    messagingSenderId: '346917753378',
    projectId: 'last-year-project-d9ba1',
    authDomain: 'last-year-project-d9ba1.firebaseapp.com',
    storageBucket: 'last-year-project-d9ba1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC17B48Ah5iUQP5rRoOucCH3p5GPsSGizY',
    appId: '1:346917753378:android:68902beefcd96c76fdb07b',
    messagingSenderId: '346917753378',
    projectId: 'last-year-project-d9ba1',
    storageBucket: 'last-year-project-d9ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLB8vzTKrziuF-3NahSNzCTbeECQWoV-M',
    appId: '1:346917753378:ios:8db017756963a2f2fdb07b',
    messagingSenderId: '346917753378',
    projectId: 'last-year-project-d9ba1',
    storageBucket: 'last-year-project-d9ba1.appspot.com',
    iosBundleId: 'com.example.baladevAssignmentPersistVenturesSoundOfMeme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLB8vzTKrziuF-3NahSNzCTbeECQWoV-M',
    appId: '1:346917753378:ios:8db017756963a2f2fdb07b',
    messagingSenderId: '346917753378',
    projectId: 'last-year-project-d9ba1',
    storageBucket: 'last-year-project-d9ba1.appspot.com',
    iosBundleId: 'com.example.baladevAssignmentPersistVenturesSoundOfMeme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHPxx-hcRbbp3tqaaHQyxMJHcuM7btny4',
    appId: '1:346917753378:web:011ab9b433be2746fdb07b',
    messagingSenderId: '346917753378',
    projectId: 'last-year-project-d9ba1',
    authDomain: 'last-year-project-d9ba1.firebaseapp.com',
    storageBucket: 'last-year-project-d9ba1.appspot.com',
  );

}